export const currency_data = {
  INR: { country: "India", currency_name: "Indian Rupee" },
  AED: { country: "United Arab Emirates", currency_name: "UAE Dirham" },
  AFN: { country: "Afghanistan", currency_name: "Afghan Afghani" },
  ALL: { country: "Albania", currency_name: "Albanian Lek" },
  AMD: { country: "Armenia", currency_name: "Armenian Dram" },
  ANG: {
    country: "Netherlands Antilles",
    currency_name: "Netherlands Antillean Guilder",
  },
  AOA: { country: "Angola", currency_name: "Angolan Kwanza" },
  ARS: { country: "Argentina", currency_name: "Argentine Peso" },
  AUD: { country: "Australia", currency_name: "Australian Dollar" },
  AWG: { country: "Aruba", currency_name: "Aruban Florin" },
  AZN: { country: "Azerbaijan", currency_name: "Azerbaijani Manat" },
  BAM: {
    country: "Bosnia and Herzegovina",
    currency_name: "Bosnia-Herzegovina Convertible Mark",
  },
  BBD: { country: "Barbados", currency_name: "Barbadian Dollar" },
  BDT: { country: "Bangladesh", currency_name: "Bangladeshi Taka" },
  BGN: { country: "Bulgaria", currency_name: "Bulgarian Lev" },
  BHD: { country: "Bahrain", currency_name: "Bahraini Dinar" },
  BIF: { country: "Burundi", currency_name: "Burundian Franc" },
  BMD: { country: "Bermuda", currency_name: "Bermudian Dollar" },
  BND: { country: "Brunei", currency_name: "Brunei Dollar" },
  BOB: { country: "Bolivia", currency_name: "Bolivian Boliviano" },
  BRL: { country: "Brazil", currency_name: "Brazilian Real" },
  BSD: { country: "Bahamas", currency_name: "Bahamian Dollar" },
  BTN: { country: "Bhutan", currency_name: "Bhutanese Ngultrum" },
  BWP: { country: "Botswana", currency_name: "Botswana Pula" },
  BYN: { country: "Belarus", currency_name: "Belarusian Ruble" },
  BZD: { country: "Belize", currency_name: "Belize Dollar" },
  CAD: { country: "Canada", currency_name: "Canadian Dollar" },
  CDF: {
    country: "Democratic Republic of Congo",
    currency_name: "Congolese Franc",
  },
  CHF: { country: "Switzerland", currency_name: "Swiss Franc" },
  CLP: { country: "Chile", currency_name: "Chilean Peso" },
  CNY: { country: "China", currency_name: "Chinese Yuan" },
  COP: { country: "Colombia", currency_name: "Colombian Peso" },
  CRC: { country: "Costa Rica", currency_name: "Costa Rican Colón" },
  CUP: { country: "Cuba", currency_name: "Cuban Peso" },
  CVE: { country: "Cape Verde", currency_name: "Cape Verdean Escudo" },
  CZK: { country: "Czech Republic", currency_name: "Czech Koruna" },
  DJF: { country: "Djibouti", currency_name: "Djiboutian Franc" },
  DKK: { country: "Denmark", currency_name: "Danish Krone" },
  DOP: { country: "Dominican Republic", currency_name: "Dominican Peso" },
  DZD: { country: "Algeria", currency_name: "Algerian Dinar" },
  EGP: { country: "Egypt", currency_name: "Egyptian Pound" },
  ERN: { country: "Eritrea", currency_name: "Eritrean Nakfa" },
  ETB: { country: "Ethiopia", currency_name: "Ethiopian Birr" },
  EUR: { country: "Eurozone", currency_name: "Euro" },
  FJD: { country: "Fiji", currency_name: "Fijian Dollar" },
  FKP: { country: "Falkland Islands", currency_name: "Falkland Islands Pound" },
  FOK: { country: "Faroe Islands", currency_name: "Faroese Króna" },
  GBP: { country: "United Kingdom", currency_name: "British Pound" },
  GEL: { country: "Georgia", currency_name: "Georgian Lari" },
  GGP: { country: "Guernsey", currency_name: "Guernsey Pound" },
  GHS: { country: "Ghana", currency_name: "Ghanaian Cedi" },
  GIP: { country: "Gibraltar", currency_name: "Gibraltar Pound" },
  GMD: { country: "Gambia", currency_name: "Gambian Dalasi" },
  GNF: { country: "Guinea", currency_name: "Guinean Franc" },
  GTQ: { country: "Guatemala", currency_name: "Guatemalan Quetzal" },
  GYD: { country: "Guyana", currency_name: "Guyanese Dollar" },
  HKD: { country: "Hong Kong", currency_name: "Hong Kong Dollar" },
  HNL: { country: "Honduras", currency_name: "Honduran Lempira" },
  HRK: { country: "Croatia", currency_name: "Croatian Kuna" },
  HTG: { country: "Haiti", currency_name: "Haitian Gourde" },
  HUF: { country: "Hungary", currency_name: "Hungarian Forint" },
  IDR: { country: "Indonesia", currency_name: "Indonesian Rupiah" },
  ILS: { country: "Israel", currency_name: "Israeli New Shekel" },
  IMP: { country: "Isle of Man", currency_name: "Manx Pound" },
  IQD: { country: "Iraq", currency_name: "Iraqi Dinar" },
  IRR: { country: "Iran", currency_name: "Iranian Rial" },
  ISK: { country: "Iceland", currency_name: "Icelandic Króna" },
  JEP: { country: "Jersey", currency_name: "Jersey Pound" },
  JMD: { country: "Jamaica", currency_name: "Jamaican Dollar" },
  JOD: { country: "Jordan", currency_name: "Jordanian Dinar" },
  JPY: { country: "Japan", currency_name: "Japanese Yen" },
  KES: { country: "Kenya", currency_name: "Kenyan Shilling" },
  KGS: { country: "Kyrgyzstan", currency_name: "Kyrgyzstani Som" },
  KHR: { country: "Cambodia", currency_name: "Cambodian Riel" },
  KID: { country: "Kiribati", currency_name: "Kiribati Dollar" },
  KMF: { country: "Comoros", currency_name: "Comorian Franc" },
  KRW: { country: "South Korea", currency_name: "South Korean Won" },
  KWD: { country: "Kuwait", currency_name: "Kuwaiti Dinar" },
  KYD: { country: "Cayman Islands", currency_name: "Cayman Islands Dollar" },
  KZT: { country: "Kazakhstan", currency_name: "Kazakhstani Tenge" },
  LAK: { country: "Laos", currency_name: "Lao Kip" },
  LBP: { country: "Lebanon", currency_name: "Lebanese Pound" },
  LKR: { country: "Sri Lanka", currency_name: "Sri Lankan Rupee" },
  LRD: { country: "Liberia", currency_name: "Liberian Dollar" },
  LSL: { country: "Lesotho", currency_name: "Lesotho Loti" },
  LYD: { country: "Libya", currency_name: "Libyan Dinar" },
  MAD: { country: "Morocco", currency_name: "Moroccan Dirham" },
  MDL: { country: "Moldova", currency_name: "Moldovan Leu" },
  MGA: { country: "Madagascar", currency_name: "Malagasy Ariary" },
  MKD: { country: "North Macedonia", currency_name: "Macedonian Denar" },
  MMK: { country: "Myanmar", currency_name: "Myanmar Kyat" },
  MNT: { country: "Mongolia", currency_name: "Mongolian Tugrik" },
  MOP: { country: "Macau", currency_name: "Macanese Pataca" },
  MRU: { country: "Mauritania", currency_name: "Mauritanian Ouguiya" },
  MUR: { country: "Mauritius", currency_name: "Mauritian Rupee" },
  MVR: { country: "Maldives", currency_name: "Maldivian Rufiyaa" },
  MWK: { country: "Malawi", currency_name: "Malawian Kwacha" },
  MXN: { country: "Mexico", currency_name: "Mexican Peso" },
  MYR: { country: "Malaysia", currency_name: "Malaysian Ringgit" },
  MZN: { country: "Mozambique", currency_name: "Mozambican Metical" },
  NAD: { country: "Namibia", currency_name: "Namibian Dollar" },
  NGN: { country: "Nigeria", currency_name: "Nigerian Naira" },
  NIO: { country: "Nicaragua", currency_name: "Nicaraguan Córdoba" },
  NOK: { country: "Norway", currency_name: "Norwegian Krone" },
  NPR: { country: "Nepal", currency_name: "Nepalese Rupee" },
  NZD: { country: "New Zealand", currency_name: "New Zealand Dollar" },
  OMR: { country: "Oman", currency_name: "Omani Rial" },
  PAB: { country: "Panama", currency_name: "Panamanian Balboa" },
  PEN: { country: "Peru", currency_name: "Peruvian Sol" },
  PGK: { country: "Papua New Guinea", currency_name: "Papua New Guinean Kina" },
  PHP: { country: "Philippines", currency_name: "Philippine Peso" },
  PKR: { country: "Pakistan", currency_name: "Pakistani Rupee" },
  PLN: { country: "Poland", currency_name: "Polish Złoty" },
  PYG: { country: "Paraguay", currency_name: "Paraguayan Guarani" },
  QAR: { country: "Qatar", currency_name: "Qatari Riyal" },
  RON: { country: "Romania", currency_name: "Romanian Leu" },
  RSD: { country: "Serbia", currency_name: "Serbian Dinar" },
  RUB: { country: "Russia", currency_name: "Russian Ruble" },
  RWF: { country: "Rwanda", currency_name: "Rwandan Franc" },
  SAR: { country: "Saudi Arabia", currency_name: "Saudi Riyal" },
  SBD: { country: "Solomon Islands", currency_name: "Solomon Islands Dollar" },
  SCR: { country: "Seychelles", currency_name: "Seychellois Rupee" },
  SDG: { country: "Sudan", currency_name: "Sudanese Pound" },
  SEK: { country: "Sweden", currency_name: "Swedish Krona" },
  SGD: { country: "Singapore", currency_name: "Singapore Dollar" },
  SHP: { country: "Saint Helena", currency_name: "Saint Helena Pound" },
  SLE: { country: "Sierra Leone", currency_name: "Sierra Leonean Leone" },
  SLL: { country: "Sierra Leone", currency_name: "Sierra Leonean Leone" },
  SOS: { country: "Somalia", currency_name: "Somali Shilling" },
  SRD: { country: "Suriname", currency_name: "Surinamese Dollar" },
  SSP: { country: "South Sudan", currency_name: "South Sudanese Pound" },
  STN: {
    country: "São Tomé and Príncipe",
    currency_name: "São Tomé and Príncipe Dobra",
  },
  SYP: { country: "Syria", currency_name: "Syrian Pound" },
  SZL: { country: "Swaziland", currency_name: "Swazi Lilangeni" },
  THB: { country: "Thailand", currency_name: "Thai Baht" },
  TJS: { country: "Tajikistan", currency_name: "Tajikistani Somoni" },
  TMT: { country: "Turkmenistan", currency_name: "Turkmenistani Manat" },
  TND: { country: "Tunisia", currency_name: "Tunisian Dinar" },
  TOP: { country: "Tonga", currency_name: "Tongan Pa'anga" },
  TRY: { country: "Turkey", currency_name: "Turkish Lira" },
  TTD: {
    country: "Trinidad and Tobago",
    currency_name: "Trinidad and Tobago Dollar",
  },
  TVD: { country: "Tuvalu", currency_name: "Tuvaluan Dollar" },
  TWD: { country: "Taiwan", currency_name: "New Taiwan Dollar" },
  TZS: { country: "Tanzania", currency_name: "Tanzanian Shilling" },
  UAH: { country: "Ukraine", currency_name: "Ukrainian Hryvnia" },
  UGX: { country: "Uganda", currency_name: "Ugandan Shilling" },
  USD: { country: "United States", currency_name: "United States Dollar" },
  UYU: { country: "Uruguay", currency_name: "Uruguayan Peso" },
  UZS: { country: "Uzbekistan", currency_name: "Uzbekistani Som" },
  VES: { country: "Venezuela", currency_name: "Venezuelan Bolívar Soberano" },
  VND: { country: "Vietnam", currency_name: "Vietnamese Dong" },
  VUV: { country: "Vanuatu", currency_name: "Vanuatu Vatu" },
  WST: { country: "Samoa", currency_name: "Samoan Tālā" },
  XAF: {
    country: "Central African Republic",
    currency_name: "Central African CFA Franc",
  },
  XCD: {
    country: "Eastern Caribbean",
    currency_name: "Eastern Caribbean Dollar",
  },
  XDR: {
    country: "International Monetary Fund",
    currency_name: "Special Drawing Rights",
  },
  XOF: {
    country: "West African Economic and Monetary Union",
    currency_name: "West African CFA Franc",
  },
  XPF: {
    country: "French Overseas Collectivities",
    currency_name: "CFP Franc",
  },
  YER: { country: "Yemen", currency_name: "Yemeni Rial" },
  ZAR: { country: "South Africa", currency_name: "South African Rand" },
  ZMW: { country: "Zambia", currency_name: "Zambian Kwacha" },
  ZWL: { country: "Zimbabwe", currency_name: "Zimbabwean Dollar" },
};
